### PR TITLE
Update jmc ELN configuration

### PR DESCRIPTION
**Pull request by jiekang**
Hi, this adds JMC which is also under sst_dotnet_java. I copied from what was done in https://github.com/minimization/content-resolver-input/pull/22

JMC is delivered as a module in Fedora, does that change anything?

### CODE REVIEW

**Comment by omajid** [comment]
@asamalik Can you help us understand how to use modules here? Is it okay to list a module under `packages`?

**Comment by asamalik** [comment]
The [workload config spec](https://github.com/minimization/content-resolver/blob/master/config_specs/workload.yaml#L84) has a `modules_enable` field you can use. And then just list your packages in `packages` and they'll get pulled in from the module.

That's basically like doing

```
$ dnf module enable module:stream
$ dnf install package1 package2 ...
```

**Comment by jiekang** [comment]
@asamalik should the module:stream be matching Fedora or RHEL 8 or is this something we can choose ourselves here?

**Comment by omajid** [comment]
AFAIK, the input to ELN is Fedora. You should be using the name of the Fedora module stream here.

I don't know what the right thing to do is if you want the module name in ELN to be different that what it is in Fedora.

**Comment by asamalik** [comment]
It takes content from Fedora, so both packages and modules are Fedora.

Module names are not propagated to the end result, just the package list, so having different module names won't be a problem here.

**Comment by jiekang** [comment]
Thank you for the information. I've updated the configuration with the `modules_enable` field.

**Comment by jiekang** [comment]
@asamalik Hi! After this PR it seems the content set for RHEL 9 still doesn't show anything for jmc.

Is this because I used the `arch_packages` section instead of `packages`?

**Comment by asamalik** [comment]
@jiekang Hi!

Using `arch_packages` is totally fine if you only want those on a subset of architectures.

Looks like those packages don't exist in Fedora Rawhide.

```
# dnf module enable jmc:latest
... output omitted ...
# dnf install jmc
Last metadata expiration check: 0:00:30 ago on Tue Aug 11 15:49:11 2020.
All matches were filtered out by modular filtering for argument: jmc
Error: Unable to find a match: jmc
```

The tooling is supposed to report when this happens, but there is a bug with the reporting for arch-specific packages. I'll fix that ASAP. With the fix, you'll see the workload as failed with the following error message:

```
The following required packages are not available:
  - jmc
  - jmc-core
```

But in the meantime, can you please check the packages `jmc` and `jmc-core` in rawhide?

**Comment by jiekang** [comment]
Ah I see, got it. Right, the rawhide builds are not successful at this time; that will be fixed shortly. Thank you for the explanation!

**Pull request merged**
