### PR TITLE
cloud experience: add efs-utils

### PR DESCRIPTION
**Pull request by major**
This package adds integrations for Elastic File System (EFS) on AWS which allows users to mount and manage EFS much more efficiently.

### CODE REVIEW

**Comment by yselkowitz** [comment]
This appears to depend on python3-botocore, which was in RHEL 8 HA but not in 9.  Will your SST be maintaining that as well?

**Comment by major** [comment]
Good catch, @yselkowitz. That slipped by me as I was testing on a system with EPEL enabled. 🤦‍♂️

Let me sync with the team and see how we want to approach this one.

**Comment by yselkowitz** [comment]
Could you please mark this as draft in the meantime?

**Comment by major** [comment]
Done. Thank you.

**Comment by major** [comment]
@yselkowitz Updated and python-botocore is added in there.

**Comment by major** [comment]
@yselkowitz My goal would be to get it into c9s/RHEL9. Sorry, this is my first one of these and I'm still reading through all of the docs.

**Review by yselkowitz — APPROVED** [review]
Thanks for clarifying.

**Pull request merged**
