### PR TITLE
sst_edge: Update SST Edge package set for el9

### PR DESCRIPTION
**Pull request by nullr0ute**
Update the el9 package set for RHEL for Edge.

Signed-off-by: Peter Robinson <pbrobinson@redhat.com>

### CODE REVIEW

**Comment by nullr0ute** [comment]
Why was this closed without merging @asamalik

**Comment by asamalik** [comment]
@nullr0ute Do you still need this in?

(It was opened over half a year ago, and no one merged it, so it felt stale. I was just closing old PRs, sorry I haven't commented here in advance, should have.)

**Comment by nullr0ute** [comment]
> @nullr0ute Do you still need this in?
> 
> (It was opened over half a year ago, and no one merged it, so it felt stale. I was just closing old PRs, sorry I haven't commented here in advance, should have.)

Yes, it's still valid. I'm not sue why it took 8 months to review

**Comment by asamalik** [comment]
Sorry, I meant do you also need it in c9s, or just eln?

**Comment by asamalik** [comment]
Probably fell through the cracks, sorry about it! I'll get it in.

**Comment by asamalik** [comment]
Any chance you can point it to the `main` branch?

**Comment by asamalik** [comment]
@nullr0ute actually, this is my messup, I'll open a new PR for you. It'll need some extra work because of the history cleanup in the repo (there's more info in the readme about it.)

So let me do that, and I'll just ping you from the new PR to confirm.

Sorry again about missing it before.

**Comment by asamalik** [comment]
OK, I thought this would be a simple cherry-pick, but there were [two commits to this file since this PR](https://github.com/minimization/content-resolver-input-archive/commits/master/configs/sst_edge.yaml), and it now conflicts. And I can't figure out what you need removed and what you need added. 

```
document: feedback-pipeline-workload
version: 1
data:
  name: edge packages
  description: Packages for edge usecases
  maintainer: sst_edge

  packages:
<<<<<<< HEAD
  - can-utils
  - greenboot
  - greenboot-reboot
  - greenboot-status
  - libgpiod-devel
  - libgpiod-utils
  - python3-libgpiod
  - libi2cd-devel
  - libiio-devel
  - libiio-utils
  - python3-iio

  # Packages co-maintained with the CoreOS SST
  - ostree
  - rpm-ostree
  - nss-altfiles
  - coreos-installer
  - coreos-installer-bootinfra
  - coreos-installer-dracut
=======
  - ostree
  - rpm-ostree
  - nss-altfiles
  - rust-coreos-installer
>>>>>>> 003d5c20 (sst_edge: Update SST Edge package set for el9)

  arch_packages:
    x86_64:
    - clevis-pin-tpm2
    - fdo-client
    - fdo-init
    - fdo-manufacturing-server
    - fdo-owner-cli
    - fdo-owner-onboarding-server
    - fdo-rendezvous-server
    - greenboot
    - greenboot-rpm-ostree-grub2
    aarch64:
    - clevis-pin-tpm2
    - fdo-client
    - fdo-init
    - fdo-manufacturing-server
    - fdo-owner-cli
    - fdo-owner-onboarding-server
    - fdo-rendezvous-server
    - greenboot
    - greenboot-rpm-ostree-grub2
    ppc64le:
    - greenboot
    - greenboot-default-health-checks

  labels:
  - eln
  - c9s
```

@nullr0ute Would you please open a new PR? I can't resolve the conflict myself, because I don't know what packages stay and what go.

**Comment by nullr0ute** [comment]
Created #773 to replace this.

**Pull request closed without merging**
