### PR TITLE
Add tracer to the sst_cs_system_management-other workload

### PR DESCRIPTION
**Pull request by FrostyX**
AFAIK we want to add tracer only because of Cockpit so I am not
creating a separate workload but adding it here.

### CODE REVIEW

**Comment by FrostyX** [comment]
I wasn't really sure if I should create a new workload or add it here (or possibly somewhere else). Please somebody point me in the right direction.

**Comment by FrostyX** [comment]
Pinging @dmach as it might interest him.

**Comment by jwboyer** [comment]
If the cockpit team will maintain this, it's correct.  If it's going to be maintained by another team, like the software management team, you should probably add it to their workload instead.

**Comment by FrostyX** [comment]
The cockpit team uses the package but I should be the one maintaining
it. Then I should probably create a workload for myself or Community
Packaging Team (CPT), that I am a part of?

**Comment by jwboyer** [comment]
After some digging, I think it would be best to just add this to configs/sst_cs_system_management-other.yaml  That's the proper owning team and we can get it assigned to you in bugzilla from there.

**Comment by FrostyX** [comment]
Thank you @jwboyer,
moved to `configs/sst_cs_system_management-other.yaml`.

**Pull request merged**
