### PR TITLE
python-crypto is bad crypto

### PR DESCRIPTION
**Pull request by hroncok**
cc @simo5, please ack

(This package just got assigned to Python Maint under a incorrect reason, so before I move it back to @lnykryn / @kdudka, I also went ahead and explicitly marked is as unwanted.)

### CODE REVIEW

**Comment by simo5** [comment]
ACK ACK ACK ACK ACK ACK ACK ACK ACK
Kill python-crypto with fire please!

**Comment by simo5** [comment]
I do not see python-crypto in the resolver, what is trying to pull it in?

**Comment by hroncok** [comment]
https://tiny.distro.builders/view-rpm--view-eln--python3-crypto.html

python3-impacket -> curl

**Comment by lnykryn** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1932082
We definitely plan to drop that dependency in beta.

čt 4. 3. 2021 v 19:44 odesílatel Miro Hrončok <notifications@github.com>
napsal:

**Comment by kdudka** [comment]
Yes, `curl-7.75.0-2.el9` tagged `rhel-9.0.0-beta-candidate` does not require `python3-impacket` any more.

**Pull request merged**
