### PR TITLE
Update fonts package list from recently updated lorax code.

### PR DESCRIPTION
**Pull request by pnemade**
See https://github.com/weldr/lorax/commit/38d9e894a13280b169c71ae6f87dbd14d2e995e9

Also, xorg-x11-fonts-misc package already removed in commit https://github.com/weldr/lorax/commit/ea0c6c3b3af5cd68477784419eb82ee196e50334

### CODE REVIEW

**Comment by yselkowitz** [comment]
RHEL and ELN have their own templates that would first need to be synced with those lorax changes: https://src.fedoraproject.org/rpms/lorax-templates-rhel/blob/eln/f/80-rhel

/cc @bstinsonmhk @sgallagher

**Comment by yselkowitz** [comment]
https://src.fedoraproject.org/rpms/lorax-templates-rhel/pull-request/8 includes the font changes.

**Comment by yselkowitz** [comment]
The updated lorax-templates-rhel has landed in an ELN compose.

**Comment by yselkowitz** [comment]
@pnemade this change has landed in ELN, resulting in the removal of the following fonts packages:

- lohit-assamese-fonts
- lohit-bengali-fonts
- lohit-devanagari-fonts
- lohit-gujarati-fonts
- lohit-kannada-fonts
- lohit-marathi-fonts
- lohit-odia-fonts
- lohit-tamil-fonts
- lohit-telugu-fonts
- sil-abyssinica-fonts

Is this the intended result?

**Comment by pnemade** [comment]
@yselkowitz Yes. Lohit Indic fonts removal is part of this F39 Change https://fedoraproject.org/wiki/Changes/Indic_Noto_fonts
We have submitted ELN comps change today for those fonts removal https://pagure.io/fedora-comps/pull-request/949

**Comment by yselkowitz** [comment]
@pnemade ok thanks for confirming.  Please note that https://src.fedoraproject.org/rpms/lorax-templates-rhel/pull-request/8 (or at least relevant parts thereof) will need to be backported to c10s, and then the aforementioned fonts packages can then be removed from c10s.

**Comment by pnemade** [comment]
Yes @tagoh is preparing for c10s MR this week.

**Pull request merged**
