### PR TITLE
Create sst_arch_hw-bluefield.yaml

### PR DESCRIPTION
**Pull request by jdonohue2**
Hope this one is good

### CODE REVIEW

**Comment by jdonohue2** [comment]
On Fri, Aug 7, 2020 at 1:04 AM Adam Samalik <notifications@github.com>
wrote:

> *@asamalik* requested changes on this pull request.
>
> Sorry, hate to be this person who's pedantic, but computers are very
> particular about their configs... I have no way to edit and quickly fix
> your config, so need to request changes again.
>

Hi Adam, I’m really sorry to create extra work for you, but I *thought*
that I had this sorted out. Obviously this is something that I don’t
normally do. I’ll have it resolved today. Thanks for your patience.

Joe

**Comment by asamalik** [comment]
This has been opened for about a week now. I can't merge it before you make requested changes, please see my comment above.

**Comment by jdonohue2** [comment]
On Thu, Aug 13, 2020 at 7:15 AM Adam Samalik <notifications@github.com>
wrote:

> This has been opened for about a week now. I can't merge it before you
> make requested changes, please see my comment above.
>

I did make the changes, but I must've done something else wrong. Looking at
it now.

**Comment by jwboyer** [comment]
I merged a separate version of this last week.

**Pull request closed without merging**
