### PR TITLE
Infra Services c10s workload updates:

### PR DESCRIPTION
**Pull request by notroj**
- restore varnish
- drop spamassassin, sendmail
- explicitly mark unwanted removed packages

### CODE REVIEW

**Comment by yselkowitz** [comment]
@notroj just noticed now that sudo has a hard `BuildRequires: sendmail`.  Is there any reason why it could not `BuildRequires: server(smtp)` or `/usr/sbin/sendmail` instead, and use whichever provider the user chooses (postfix for RHEL 10, but Fedora has lots of choices) at runtime, or is sudo really only compatible with sendmail?

**Comment by yselkowitz** [comment]
Actually, looking closer at sudo's sources, it looks like we could just configure --with-sendmail=/usr/sbin/sendmail and not BuildRequires it at all?

**Comment by yselkowitz** [comment]
> Actually, looking closer at sudo's sources, it looks like we could just configure --with-sendmail=/usr/sbin/sendmail and not BuildRequires it at all?

https://src.fedoraproject.org/rpms/sudo/pull-request/27

**Comment by notroj** [comment]
A big thank you @yselkowitz 

```
+ dnf repoquery -q --whatdepends /usr/sbin/sendmail
redhat-lsb-core-0:4.1-56.el9.i686
redhat-lsb-core-0:4.1-56.el9.x86_64
```
```
+ dnf repoquery -q --whatdepends sendmail
e2scrub-0:1.46.5-5.el9.x86_64
...
```

I guess the first one is OK, but not the second one. I see there is already a PR for this too

https://src.fedoraproject.org/rpms/e2fsprogs/pull-request/6

**Comment by yselkowitz** [comment]
Actually, neither show up as affecting ELN: https://tiny.distro.builders/view-rpm--view-eln--sendmail.html (which will go away once the sudo PR is merged and goes through the pipeline).  redhat-lsb-core has been removed from RHEL, and e2scrub (subpackage of e2fsprogs) is built but not shipped in ELN or RHEL either.  It still wouldn't hurt to change the hardcoded `sendmail` dependency to something more generic though, even if "just" for Fedora's benefit.

**Pull request merged**
