### PR TITLE
Add glew to desktop unwanted ELN packages

### PR DESCRIPTION
**Pull request by nwnk**
Comment should be self-explanatory.

### CODE REVIEW

**Comment by jwboyer** [comment]
@nwnk I just notice this file doesn't have the c9s label.  That means it won't be reflected in CentOS Stream 9.  If that's expected, then no issues.  If you want it to be though, work with @asamalik to get it squared away in a separate PR.

**Comment by nwnk** [comment]
> @nwnk I just notice this file doesn't have the c9s label. That means it won't be reflected in CentOS Stream 9. If that's expected, then no issues. If you want it to be though, work with @asamalik to get it squared away in a separate PR.

I can't _set_ labels, here, so yeah I'll have to do that.

**Comment by asamalik** [comment]
@nwnk It's the `labels` field in the file:

```
labels:
  - eln
```

If you want it to be in CentOS Stream 9, you need to add `c9s` there, too:

```
labels:
  - eln
  - c9s
```

**Comment by nwnk** [comment]
On reflection this really is ELN-only, it wants excluding because it wants not to be in RHEL. It's fine for CentOS to have a build though since other things in Fedora do use it.

**Pull request merged**
