### PR TITLE
kde: marknote replaces knotes

### PR DESCRIPTION
**Pull request by yselkowitz**
/cc @tdawson

### CODE REVIEW

**Review by sgallagher — APPROVED** [review]
The Fedora packager commit looks good to me.

**Comment by tdawson** [comment]
The KDE stuff looks good.
Why do we have git in Fedora Packager, and eln-extra group?

**Comment by tdawson** [comment]
Actually, let me take back my statement about KDE.  Why are we replacing knote with marknote.  From what I see, they do two totally different things.

**Comment by yselkowitz** [comment]
see: https://invent.kde.org/pim/pim-technical-roadmap/-/issues/58

**Comment by yselkowitz** [comment]
see https://invent.kde.org/pim/pim-technical-roadmap/-/issues/58

**Comment by tdawson** [comment]
Thank you for the explanation.  If that is the case, then I give a thumbs up to the KDE section.

**Comment by yselkowitz** [comment]
> Why do we have git in Fedora Packager, and eln-extra group?
 Copied straight from the epel9 comps.

**Pull request merged**
