### PR TITLE
Add deps of nodejs for proper WASM rebuilds

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by yselkowitz** [comment]
These are still bundled in rawhide and hence ELN.  Will that be changing?

**Comment by hhorak** [comment]
> These are still bundled in rawhide and hence ELN. Will that be changing?

Yes, this should get unbundled in Fedora and ELN as well -- @khardix are there some unresolved obstacles for the unbundling in Fedora Rawhide that we track?

**Comment by yselkowitz** [comment]
First off, nodejs-cjs-module-lexer is currently FTBFS: https://koji.fedoraproject.org/koji/packageinfo?packageID=38748

**Comment by yselkowitz** [comment]
And a attempted scratch rebuild of wasi-libc also failed: https://koji.fedoraproject.org/koji/taskinfo?taskID=124251326

**Comment by khardix** [comment]
> @khardix are there some unresolved obstacles for the unbundling in Fedora Rawhide that we track?

Still the same – how to make the re-built modules shared between streams. I did not find an existing ticket, so I filed one: https://bugzilla.redhat.com/show_bug.cgi?id=2316095

> nodejs-cjs-module-lexer is currently FTBFS

Due to the general nodejs propensity for bundling and adding new (build) dependencies whenever a shiny new toy appear, intermittent FTBFS are to be expected, unfortunately. I'm aware of the issue and working on a solution.

> wasi-libc also failed

There is a test that checks that the macros defined in various LIBC headers are as expected; it needs to be updated manually whenever the build environment changes. I'll take look at it.

**Review by yselkowitz — APPROVED** [review]
All these build again successfully in ELN.

**Pull request merged**
