### PR TITLE
Add vulkan-utility-libraries

### PR DESCRIPTION
**Pull request by jexposit**
The vulkan-utility-libraries package is required to build the Vulkan SDK (v1.3.268.0).

For more information please check:
https://github.com/KhronosGroup/Vulkan-Utility-Libraries#readme

JIRA issue: https://issues.redhat.com/browse/RHEL-15445
Fedora: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2247640

### CODE REVIEW

**Comment by yselkowitz** [comment]
This config file is for both c9s and eln, is this package being added to both?

**Comment by jexposit** [comment]
Hi @yselkowitz,

Yes. `vulkan-utility-libraries` will be a dependency of `vulkan-validation-layers` once it gets included, so it is required whenever the later is required.

**Comment by yselkowitz** [comment]
@jexposit this package does not currently exist in Fedora, which is causing a (non-fatal) warning in this workload.  Was this added prematurely?

**Comment by jexposit** [comment]
@yselkowitz I linked in my first comment the Fedora inclusion request:
https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2247640

I opened it 2 weeks ago but so far it hasn't received much feedback. Hopefully it'll be added to Fedora soon.

**Comment by yselkowitz** [comment]
@jexposit even though the package is in Fedora now, the warning persists in Content Resolver, the reason being is that this package provides only static libraries, and therefore there is no `vulkan-utility-libraries` RPM, only ``vulkan-utility-libraries-devel`.  This needs to be fixed in the config through a new PR.

**Comment by jexposit** [comment]
Oh true! Sorry about that, fixed in https://github.com/minimization/content-resolver-input/pull/1024

**Pull request merged**
