### PR TITLE
Update Content Set files for Virt SST and Virt Windows SST

### PR DESCRIPTION
**Pull request by yashkmankad**
Virt SST:
 - Move mingw-* packages required by libguestfs to Virt SST.
   Rich Jones will be maintaining them
 - Add ninja-build and meson
 - Remove spice packages libphodav and spice5-html

Virt Windows SST:
 - Add mingw-* packages required by virtio-win.
   Basil will be maintaining them.

Signed-off-by: Yash Mankad <ymankad@redhat.com>

### CODE REVIEW

**Comment by yashkmankad** [comment]
@asamalik  - Hi Adam, I might make a couple more changes before tomorrow, so could you hold off on merging it till I confirm ?

**Comment by jwboyer** [comment]
@yashkmankad is this one ready to merge now?

**Comment by yashkmankad** [comment]
@jwboyer @asamalik -- thank you for being patient. Now it is.

I was asked to drop a few dependencies from the 'required' list to see if they come back.

**Comment by asamalik** [comment]
Cool, let's see!

**Pull request merged**
