### PR TITLE
Add a placeholder for pip to filter out many tests deps

### PR DESCRIPTION
**Pull request by hroncok**
cc @torsava @encukou 

@asamalik Am I doing it right? python-pip is the source name, the other two are subpackages.

### CODE REVIEW

**Comment by hroncok** [comment]
I've amended this based on https://github.com/minimization/content-resolver/blob/master/config_specs/workload.yaml

No idea if this is how to have 2 subpackages.

**Comment by asamalik** [comment]
@hroncok yes, you're doing it right

**Comment by hroncok** [comment]
@asamalik Could you please let me know when I can examine the result on tiny.distro.builders?

**Comment by torsava** [comment]
@asamalik IIRC it was mentioned on the discussion that this approach might only work for leaf packages, is that true? Because plenty of stuff is going to require python3-pip.

**Comment by asamalik** [comment]
@hroncok It refreshes every ~90 mins, so this should be already live.

@torsava You are correct. This doesn't mangle the depsolver, so if python-pip gets pulled in by other packages, both the proper package and the placeholder show up.

**Comment by asamalik** [comment]
And exactly that happened, yes, python-pip is there twice now. Sorry @hroncok I misunderstood your intention, thought it's just a leaf package...

**Comment by hroncok** [comment]
OK. revert this?

**Comment by asamalik** [comment]
It's being pulled in by `micropipenv`: https://tiny.distro.builders/view-rpm--view-eln--python3-pip.html

Sure, I'll revert it

**Comment by torsava** [comment]
@asamalik So, do we understand it correctly that the only 2 ways to get rid of the unwanted dependency of python3-pip is to:

1. Do a conditional in Fedora, which we can't since the maintainer objects.
2. Wait until April and in the meantime keep the RHEL 9 content set incorrect?

**Pull request merged**
