### PR TITLE
Add automotive packages to ELN extras

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Adding qm and vhost-device-sound to ELN Extras.

### CODE REVIEW

**Comment by yselkowitz** [comment]
This would be fine, except that we're going to wind down ELN Extras, as it did not serve its intended purpose to help with EPEL branching.  Stay tuned for EPEL 10 announcements and beyond.

**Comment by yselkowitz** [comment]
@sandrobonazzola further discussions on ELN Extras have revealed the need for it to continue for a while longer.  It has been rebootstrapped and is ready for further additions, so if you can reopen this I'll merge it.

**Comment by sandrobonazzola** [comment]
@yselkowitz  I'll send a new PR, a couple of packages have been added to Fedora in the meanwhile.
Other than adding the packages here, is there anything else to be done in order to trigger the automated build from Rawhide?

**Comment by sandrobonazzola** [comment]
Opened #1243

**Pull request closed without merging**
