### PR TITLE
Add man-pages

### PR DESCRIPTION
**Pull request by nforro**

### CODE REVIEW

**Comment by jwboyer** [comment]
We should probably include man-pages-overrides as well, right?

**Comment by nforro** [comment]
man-pages-overrides is a downstream-only package, it doesn't exist in Fedora.

**Comment by jwboyer** [comment]
OK, I'll merge this now, but you can add packages that are not in Fedora with a package placeholder entry.  You might want to do that with a separate commit.

**Comment by nforro** [comment]
Done in #449.

**Pull request merged**
