### PR TITLE
Create sst_security_crypto-unwanted.yaml

### PR DESCRIPTION
**Pull request by simo5**
Adding list specifically maintained by us instead of common list maintained by bakery

### CODE REVIEW

**Comment by asamalik** [comment]
This has been opened for about a week now. I can't merge it before you make requested changes, please see my comment above.

**Comment by simo5** [comment]
@asamalik sorry I was on PTO, I'll take care of this asap

**Comment by simo5** [comment]
@asamalik the last commit should fix it, sorry for using the wrong template.

**Comment by asamalik** [comment]
No worries! Looks good, thanks.

**Pull request merged**
