### PR TITLE
Add python3-installer and python3-pyproject-hooks to Python CRB workload

### PR DESCRIPTION
**Pull request by hroncok**
Depends-on: https://src.fedoraproject.org/rpms/python-pyproject-hooks/pull-request/2

cc @torsava

### CODE REVIEW

**Comment by hroncok** [comment]
cc @torsava

**Comment by jwboyer** [comment]
Thank you for the do not merge notice.  I'll wait until that's removed.  This is where Gitlab's Draft feature would help :)

**Comment by jwboyer** [comment]
> > This is where Gitlab's Draft feature would help :)
> 
> This PR is actually marked as Draft (although I mistakenly not opened it as such immediately, but only changed it right after opening it).

Yep, caught that immediately after I hit the comment button.  Thanks

**Comment by yselkowitz** [comment]
No objections once pyproject-hooks deps are pruned through that PR.

**Pull request merged**
