### PR TITLE
Drop gfs2-utils

### PR DESCRIPTION
**Pull request by andyprice**
gfs2 is being removed in RHEL 10

### CODE REVIEW

**Comment by andyprice** [comment]
It seems I've missed some prerequisite steps of the package removal process so I'm closing this for now.

**Comment by yselkowitz** [comment]
@andyprice Actually, this is the first step in package removal for a listed package.  What did you think was missing?

**Comment by andyprice** [comment]
@yselkowitz It looked like the comps changes needed to be merged before anything else, but if this is still valid then we can keep it alive.

**Comment by andyprice** [comment]
This is the relevant Jira btw https://issues.redhat.com/browse/RHELMISC-6392

**Pull request merged**
