### PR TITLE
[sst_cloud_experience] Add opentelemetry-collector

### PR DESCRIPTION
**Pull request by major**
Adding a package for the opentelemetry collector as well as AWS Cloudwatch configuration files.

### CODE REVIEW

**Comment by yselkowitz** [comment]
@major I can't find such a package in Fedora, nor any review requests for it to be added.  Is this going to be a RHEL-specific package?  If so, it needs to be handled as a placeholder.

**Comment by major** [comment]
Thanks for catching that, @yselkowitz. I've submitted a new patch.

**Comment by yselkowitz** [comment]
Thanks for clarifying.  That placeholder syntax is deprecated, but unfortunately still commonly used as we haven't updated all uses of it in CR.  (Another thing we need to look at after RHEL 10 branching.)  Please use this as an example of the new syntax: https://github.com/minimization/content-resolver-input/blob/main/configs/sst_insights.yaml#L12

**Comment by major** [comment]
Thank you! I've just updated the patch to follow the new syntax.

**Pull request merged**
