### PR TITLE
Updated packaged for automotive base image

### PR DESCRIPTION
**Pull request by RajeshKumarSrivastava**
Added packages for the automotive base image

### CODE REVIEW

**Comment by RajeshKumarSrivastava** [comment]
@asamalik please review and merge

**Comment by juanje** [comment]
@RajeshKumarSrivastava Those are the final packages or the packages that will be used to revolve the dependencies?

**Comment by juanje** [comment]
LGTM!

**Comment by thrix** [comment]
\o/

**Comment by RajeshKumarSrivastava** [comment]
@asamalik can you please review and merge this PR, thanks!

**Pull request merged**
