### PR TITLE
sst_coreos: Update package list for C9S

### PR DESCRIPTION
**Pull request by travier**
- Enable C9S for the CoreOS SST
- Add package: butane
- Add sub-packages:
    - coreos-installer-bootinfra
    - coreos-installer-dracut
    - ignition-validate
- Mark bootupd as x86-64 & aarch64 only
- Clarify the list of packages co-maintained with the Edge SST
- Remove packages effectively maintained by other SSTs
- Remove ignition from the Edge SST

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
Looks sane to me!

**Comment by travier** [comment]
Mirno update:
- add coreos-installer-bootinfra
- add bootupd to aarch64

**Comment by travier** [comment]
Gentle ping for review @jwboyer

**Comment by jwboyer** [comment]
Apologies for the delay!

**Pull request merged**
