### PR TITLE
Drop java-1.8.0-openjdk & java-11-openjdk from ELN

### PR DESCRIPTION
**Pull request by gnu-andrew**
Drop older JDKs from ELN

### CODE REVIEW

**Comment by yselkowitz** [comment]
You'll need to split out the c9s config where 1.8 and 11 will remain from the eln (and future c10s) configs where these will be dropped.

**Comment by yselkowitz** [comment]
1. `cp configs/sst_java-java.yaml configs/sst_java-java-c9s.yaml`
2. `cp configs/sst_java-unwanted.yaml configs/sst_java-unwanted-c9s.yaml`
3. `git add configs/sst_java-java-c9s.yaml configs/sst_java-unwanted-c9s.yaml`
4. remove `eln` tag from the `c9s` configs and `c9s` tag from the "main" configs
5. move 1.8.0/11 from wanted to unwanted in the "main" configs (basically, the PR in its current state)
6. `git commit -a`

**Comment by yselkowitz** [comment]
BTW, there are still a number of packages which (Build)Require 1.8.0 or 11 -- at least byteman and jmc explicitly require 11, but possibly more.

**Comment by gnu-andrew** [comment]
> 1. `cp configs/sst_java-java.yaml configs/sst_java-java-c9s.yaml`
> 
>     2. `cp configs/sst_java-unwanted.yaml configs/sst_java-unwanted-c9s.yaml`
> 
>     3. `git add configs/sst_java-java-c9s.yaml configs/sst_java-unwanted-c9s.yaml`
> 
>     4. remove `eln` tag from the `c9s` configs and `c9s` tag from the "main" configs
> 
>     5. move 1.8.0/11 from wanted to unwanted in the "main" configs (basically, the PR in its current state)
> 
>     6. `git commit -a`

Thanks. Done. The original commit is now preceded by backing up the original files into ones with a `-c9s` suffix, and we drop `c9s` from the main config in a subsequent commit.

Feel free to squash the three into one on merge. I just thought leaving the workings there might make it easier to review and avoid looking over the original commit again.

**Comment by gnu-andrew** [comment]
> BTW, there are still a number of packages which (Build)Require 1.8.0 or 11 -- at least byteman and jmc explicitly require 11, but possibly more.

Yeah, a reason to do this as early as possible is to shake out any such dependent packages so their maintainers can fix them up.

**Review by yselkowitz — CHANGES_REQUESTED** [review]
Nitpick: the `description` of configs/sst_java-unwanted.yaml needs to be updated, but otherwise looks good.

**Pull request merged**
