### PR TITLE
edge: add can-utils, libgpiod, libi2cd, libiio

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by ikerexxe** [comment]
You forgot to add `libgpiod`, `libgpiod-c++`, `libi2cd`, `libiio` and `libiio-doc`. I guess that you omitted `libgpiod-c++` and `libiio-doc` intentionally, but the rest of the packages should be included.

**Comment by yselkowitz** [comment]
From what I've seen in other sst_* files, the -devel is enough to pull in its runtime library dependencies, but I'll let a maintainer of this repo have the final say on that.

**Comment by asamalik** [comment]
It'll pull in dependencies for you. Listing packages explicitly shows what your intention is. For example, if a dependency is no longer needed in the future, it disappears, unless you list it.

Let me know what you prefer.

**Comment by yselkowitz** [comment]
Thanks, please proceed as filed.

**Pull request merged**
