### PR TITLE
i18n input-methods: change Japanese IME from ibus-kkc to ibus-anthy

### PR DESCRIPTION
**Pull request by juhp**
https://fedoraproject.org/wiki/Changes/ibus-anthy_for_default_Japanese_IME

### CODE REVIEW

**Comment by jwboyer** [comment]
@juhp Does this mean we don't want ibus-kkc at all?  If so, it probably needs to be added to the unwanted list.

**Comment by juhp** [comment]
Okay fair point.

**Comment by juhp** [comment]
Could I do that afterwards/later?  Since we don't have a unwanted pipeline yet for i18n.
Or do you prefer to wait for that?

**Comment by jwboyer** [comment]
@asamalik do you have a preference?  I know things are in-flight at the moment.

**Comment by asamalik** [comment]
Let's get this change merged so we can see it on the output. The unwanted package is just a marker for humans to see, it doesn't have an actual functionality in Content Resolver (like it won't affect the dep solving).

**Comment by juhp** [comment]
Ping :)

**Comment by asamalik** [comment]
Sorry!

**Pull request merged**
