### PR TITLE
coreos: Fix bootupd name

### PR DESCRIPTION
**Pull request by cgwalters**
And while we have the patient open, clarify the comment.

### CODE REVIEW

**Comment by cgwalters** [comment]
How long until https://tiny.distro.builders/workload--sst_coreos--fedora-empty-base--repository-fedora-eln--x86_64.html is fixed?

**Comment by asamalik** [comment]
I don't see the error there anymore, so, now. :)

**Comment by asamalik** [comment]
Otherwise it refreshes every ~80 mins.

**Comment by cgwalters** [comment]
Ah OK and looking at that page I see this broke ppc64le/s390x; is there an equivalent of [rpm-ostree architecture conditionals](https://github.com/coreos/fedora-coreos-config/blob/eef052a9e03959f012585dc89e6575fb00f2dfd9/manifests/fedora-coreos-base.yaml#L172) here?

**Pull request merged**
